version: "3.3"

#Define services
services:
  springboot-app:
    #The docker file in BE, build the jar and provides the docker image.
    build: ./spring-boot-server
    container_name: springboot-app
    #Environment variable for Spring Boot Application.
    environment:
      MYSQL_HOST: 'mysql-db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: 'tutorials'
    ports:
      - 8080:8080 #Forwards the exposed port 8080 on the container to port 8080 on the host machine
    networks:
      mynetwork:
        ipv4_address: 10.0.0.3


  angular-app:
    #The docker file in FE, builds and provides the docker image.
    build: ./angular-8-client
    container_name: angular-app
    ports:
      - 8081:8081 #Forwads the exposed port 8081 on the container to port 8081 on the host machine
    networks:
      mynetwork:
        ipv4_address: 10.0.0.4  

networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
