version: "3.3"

services:
  springboot-app:
    image: backend-app
    container_name: springboot-app
    environment:
      MYSQL_HOST: 'mysql-db:3306'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: 'tutorials'
    ports:
      - 8080:8080  
    networks:
          - shared-network
networks:
  shared-network:
    external: true