version: "3.3"

services:
  frontend-app:
    image: frontend-app
    container_name: frontend-app
    ports:
      - 3000:3000  
    networks:
          - shared-network
networks:
  shared-network:
    external: true