name: Build, Test, and Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'spring-boot-server' # Replace 'subpath' with the actual subpath of your project

      - name: Build with Maven
        working-directory: 'subpath' # Replace 'subpath' with the actual subpath of your project
        run: mvn clean package -DskipTests

      - name: Run tests
        working-directory: 'subpath' # Replace 'subpath' with the actual subpath of your project
        run: mvn test

      - name: Build Docker image
        working-directory: 'subpath' # Replace 'subpath' with the actual subpath of your project
        run: |
          docker build -t backend-app -f Dockerfile .

